version: "3.8"

services:

  airsonic:
    container_name: airsonic
    image: lscr.io/linuxserver/airsonic-advanced:latest
    devices:
      - /dev/snd:/dev/snd
    labels:
      - deunhealth.restart.on.unhealthy=true
      - diun.enable=true
      - com.centurylinklabs.watchtower.enable=true
    environment:
      - TZ=Europe/Paris
      - JAVA_OPTS=-Xms256m -Xmx256m
    volumes:
      - nfs_playlists:/playlists
      - nfs_podcasts:/podcasts
      - ${path_mountpoint_music}:/music
      - nfs_config:/config
    ports:
      - ${port}:4040
    restart: unless-stopped
    networks:
      - frontend

volumes:
  nfs_config:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${address},rw,soft,nfsvers=4
      device: ${path_nfs_config}
  nfs_playlists:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${address},rw,soft,nfsvers=4
      device: ${path_nfs_playlists}
  nfs_podcasts:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${address},rw,soft,nfsvers=4
      device: ${path_nfs_podcasts}

networks:
  frontend:
    external: true