version: "3.8"

services:

  nextcloud-app:
    container_name: nextcloud-app
    image: nextcloud:latest
    labels:
      - deunhealth.restart.on.unhealthy=true
      - diun.enable=true
      - com.centurylinklabs.watchtower.enable=true
    environment:
      - MYSQL_PASSWORD=${databasePassword}
      - MYSQL_DATABASE=${databaseName}
      - MYSQL_USER=${databaseUser}
      - MYSQL_HOST=nextcloud-db
      - OVERWRITEPROTOCOL=https #pour permettre le bon fonctionnement du client Windows/Linux
      - NEXTCLOUD_TRUSTED_DOMAINS=${trustedDomains}
      - PHP_MEMORY_LIMIT=1024M
      - PHP_MAX_EXECUTION_TIME=300
      - PHP_UPLOAD_LIMIT=512M
    volumes:
      - nfs_app:/var/www/html
      - ${path_mountpoint_documents}:/smb-documents:ro
      - ${path_mountpoint_media}:/smb-media:ro
    ports:
      - ${port}:80
    restart: unless-stopped
    networks:
      - frontend
      - backend
    depends_on:
      - nextcloud-db

  nextcloud-db:
    container_name: nextcloud-db
    image: mariadb:latest
    labels:
      - deunhealth.restart.on.unhealthy=true
      - diun.enable=true
      - com.centurylinklabs.watchtower.enable=true
    environment:
      - MYSQL_ROOT_PASSWORD=${databaseRootPassword}
      - MYSQL_PASSWORD=${databasePassword}
      - MYSQL_DATABASE=${databaseName}
      - MYSQL_USER=${databaseUser}
    volumes:
      - db:/var/lib/mysql
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --skip-innodb-read-only-compressed
    restart: unless-stopped
    networks:
      - backend

volumes:
  nfs_app:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${address},rw,soft,nfsvers=4
      device: ${path_nfs_app}
  db:

networks:
  frontend:
    external: true
  backend:
    external: true