version: "3.8"

services:

  photoprism-chris:
    container_name: photoprism-chris
    image: photoprism/photoprism:latest
    labels:
      - deunhealth.restart.on.unhealthy=true
      - diun.enable=true
      - com.centurylinklabs.watchtower.enable=true
    environment:
      - PHOTOPRISM_ADMIN_PASSWORD=${admin_password} # Votre mot de passe admin si vous desactiver le mode public
      - PHOTOPRISM_DEBUG=false # Pour basculer en mode debuggage
      - PHOTOPRISM_PUBLIC=false # Pour désactiver l'accès par mot de passe
      - PHOTOPRISM_READONLY=false # Si vrai, bascule le répertoire originals en lecture seule, ce qui restreint les fonctionnalités
      - PHOTOPRISM_UPLOAD_NSFW=true
      - PHOTOPRISM_DETECT_NSFW=false
      - PHOTOPRISM_EXPERIMENTAL=true # Permet d'utiliser des fonctionnalités expérimentales
      - PHOTOPRISM_SITE_URL=${url} # URL d'accès
      - PHOTOPRISM_SITE_TITLE=${title}
      - PHOTOPRISM_SITE_CAPTION=${caption}
      - PHOTOPRISM_SITE_DESCRIPTION=${description}
      - PHOTOPRISM_SITE_AUTHOR=${author}
      - PHOTOPRISM_HTTP_HOST=0.0.0.0
      - PHOTOPRISM_HTTP_PORT=${port}
      - PHOTOPRISM_SETTINGS_HIDDEN=false # Pour permettre de cacher l'accès aux paramétrages
      - PHOTOPRISM_DATABASE_DRIVER=mysql
      - PHOTOPRISM_DATABASE_DSN=${databaseUser}:${databasePassword}@tcp(photoprism-db:${databasePort})/${databaseName}?charset=utf8mb4,utf8&parseTime=true
      - PHOTOPRISM_SIDECAR_JSON=true # Creer automatiquement un fichier JSON pour chaque photo grâce à Exiftool
      - PHOTOPRISM_SIDECAR_YAML=true # Creer automatiquement un fichier YAML contenant les mots clefs pour chaque photo
      - PHOTOPRISM_THUMB_FILTER=lanczos # blackman, lanczos, cubic, linear (filtre pour la création des vignettes, du meilleur au pire)
      - PHOTOPRISM_THUMB_UNCACHED=true # Pour creer les vignettes à la demande
      - PHOTOPRISM_THUMB_SIZE=1024 # Taille max des vignettes créés par defaut (default 2048, min 720, max 7680)
      - PHOTOPRISM_THUMB_SIZE_UNCACHED=1024 # Taille max des vignettes créés à la demande (default 7680, min 720, max 7680)
      - PHOTOPRISM_JPEG_SIZE=1024 # Taille max en pixels pour les images RAW converties (720-30000)
      - PHOTOPRISM_JPEG_QUALITY=92 # Mettre 95 pour des vignettes de hautes qualités (25-100)
      - PHOTOPRISM_DARKTABLE_PRESETS=false # Use darktable presets (disables concurrent raw to jpeg conversion)
    volumes:
      - ${path_mountpoint_photoprism_import}:/photoprism/import # Repertoire d'import
      - ${path_mountpoint_photoprism_originals}:/photoprism/originals # Répertoire où seront stockées les photos importées
      - nfs_storage:/photoprism/storage # Répertoire pour les paramétrages, les index, les miniatures
    ports:
      - ${port}:2343
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    restart: unless-stopped
    networks:
      - frontend
      - backend

  photoprism-db:  
    container_name: photoprism-db
    image: mariadb:10.5
    labels:
      - deunhealth.restart.on.unhealthy=true
      - diun.enable=true
      - com.centurylinklabs.watchtower.enable=true
    environment:
      - MYSQL_ROOT_PASSWORD=${databaseRootPassword}
      - MYSQL_USER=${databaseUser}
      - MYSQL_PASSWORD=${databasePassword}
      - MYSQL_DATABASE=${databaseName}
    volumes:
      - db:/var/lib/mysql
    ports:
      - ${databasePort}:3307
    command: mysqld --port=3307 --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512 --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=50
    restart: unless-stopped
    networks:
      - backend

volumes:
  nfs_storage:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${address},rw,soft,nfsvers=4
      device: ${path_nfs_storage}
  db:

networks:
  frontend:
    external: true
  backend:
    external: true