version: "3.8"

services:

  podgrab:
    container_name: podgrab
    image: akhilrex/podgrab:latest
    labels:
      - deunhealth.restart.on.unhealthy=true
      - diun.enable=true
      - com.centurylinklabs.watchtower.enable=true
    environment:
      - CHECK_FREQUENCY=30 # Fréquence de rafraichissement en min
      - PASSWORD=${password} # Optionel, le username = podgrab
    volumes:
      - nfs_config:/config
      - nfs_assets:/assets
    ports:
      - ${port}:8080 # Modifier à 7080 car mon port 8080 est déjà utilisé
    restart: unless-stopped
    networks:
      - frontend

volumes:
  nfs_config:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${address},rw,soft,nfsvers=4
      device: ${path_nfs_config}
  nfs_assets:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${address},rw,soft,nfsvers=4
      device: ${path_nfs_assets}

networks:
  frontend:
    external: true